# https://github.com/dart-lang/lints#migrating-from-packagepedantic
include: package:lints/recommended.yaml

analyzer:
  exclude:
    - example/**/*.dart
  language:
    strict-casts: true
linter:
  rules:
    overridden_fields: false
